"""Assemble a substantive revision directly from completed numeric evidence."""
from pathlib import Path
import json,re,numpy as np
ROOT=Path(__file__).resolve().parents[1];R=ROOT/'revision_20261009';M=R/'manuscript';M.mkdir(exist_ok=True)
def read(p):return json.loads((R/p).read_text(encoding='utf-8'))
eco={t:read(f'results/expanded_comparison_{t}_support_matched_baselines.json') for t in ('tou','flat')}
net=read('network_revision_summary.json');ctrl=read('results/control_transfer_summary.json')
res=read('results/resource_comparison_tou.json');ext=read('results/storenet_frozen_external.json')
def pair(t,method,cohort='all299',reference='msecont'):
 return eco[t]['cohorts'][cohort]['paired'][f'{method}_{t}_seed11_expanded__minus__{reference}_{t}_seed11_expanded']
def money(x):return f'{x*100:.3f}'
def interval(x,scale=100):return f'{x[0]*scale:.3f} to {x[1]*scale:.3f}'
def nc(group,panel=0,reference='msecont',**conditions):
 for q in net['selected_comparisons'][group]:
  if q['reference']==reference and q['key'][0]==panel and all(q['key'][i]==v for i,v in conditions.items()):return q
 raise KeyError((group,panel,reference,conditions))
def blocks(text):
 out=[]
 for p in re.split(r'\n\s*\n',text.strip()):
  p=p.strip()
  if not p:continue
  kind='heading' if re.match(r'^\d+(\.\d+)?\.?(?:\s)',p) and '\n' not in p and len(p)<130 else 'paragraph'
  if p.startswith('[[EQ_'):kind='equation'
  out.append({'type':kind,'text':p})
 return out
def table(caption,headers,rows,note):return {'type':'table','caption':caption,'headers':headers,'rows':rows,'note':note}
def figure(n,name,caption,note):return {'type':'figure','path':str(R/'figures'/f'figure{n}_{name}.preview.png'),'caption':f'Fig. {n}. {caption}','note':note}
title='When does decision-focused learning add value to residential battery control? Private costs and AC feeder consequences'
d=pair('tou','dfl');cal=pair('tou','calibrated3');saa=pair('tou','stochastic20');sd=pair('tou','stochastic20',reference='dfl')
abstract=f'''Decision-focused learning can change residential battery schedules without improving physical forecasts, but its value relative to simpler calibration and scenario control remains an engineering choice. We evaluate matched training objectives and practical alternatives using public Ausgrid household traces, simulated batteries and AC feeder models. On 108,641 paired household-days, decision-focused learning reduces operating cost by {money(-d['micro_mean_difference'])} Australian cents per day relative to continued squared-error training. Three trainable offsets capture {100*cal['micro_mean_difference']/d['micro_mean_difference']:.1f}% of this benefit; 20-scenario control achieves a further {money(-sd['micro_mean_difference'])}-cent reduction relative to decision-focused learning. The latter provides no uniform voltage advantage over scenario control. Its matched voltage-exposure reduction is appreciable in the high-source-voltage benchmark, much smaller at lower source settings, and absent in two alternative networks without screening-band excursions. Phase-resolved AC sensitivities explain how altered battery injections transmit the signal adjustment. Deployable load substitutions separate poor frozen-signal transport from successful matched retraining. Continuous state-of-charge replay retains a cost benefit after inventory adjustment. Frozen transfer to ten Irish PV households supports time-of-use savings, while flat-price savings are inconclusive. These results identify where a task-trained deterministic signal provides a modest additional benefit and where calibration or uncertainty representation should take priority. The evidence concerns quasi-static constructed feeders and modeled operating costs, rather than field voltage compliance or battery lifetime.'''
intro=(M/'introduction.txt').read_text(encoding='utf-8')
intro=intro.replace('Feeder consequences require a separate assessment.', 'Feeder consequences require a separate assessment. Low-voltage PV–battery strategy comparisons already evaluate voltage and loss impacts [L35]. Recent Electric Power Systems Research studies address distributed-battery phase balancing [L36], stochastic storage flexibility [L37] and open-source predictive flexibility control [L38]. Grid-aware smart-home management also explicitly represents conflicting private and network objectives [L39]. These approaches optimize or coordinate system services, whereas the present comparison isolates the consequences of a separable, private-cost signal learner.')
methods=(M/'methods_foundation.txt').read_text(encoding='utf-8')
methods=methods.replace('Training and scheduling times are measured in isolated, single-thread processes on the same fixed sample counts.', 'Training and scheduling times are measured in serial, single-thread method subprocesses on fixed sample counts. Unrelated revision experiments run concurrently, so measured wall time is not an idle-machine speed claim; process CPU time is also retained.')
methods=methods.replace('Both fit only training examples', 'Both use the original frozen supervised PV checkpoint and reference HGB load forecast. They fit only training examples')
methods=methods.replace('The residual-scenario controller minimizes', 'The residual-scenario controller uses the original frozen supervised PV checkpoint and reference HGB load forecast, rather than the continued-MSE checkpoint, and minimizes')
methods=methods.replace('Primary contrasts average paired daily differences across three seeds before calendar-block resampling. New fixed-model engineering comparisons use seed 11 and explicitly retain that narrower training-replication scope.', 'The original deployment-cell contrasts and external seed-mean contrasts average paired daily differences across three seeds before calendar-block resampling. The expanded comparison in the Abstract, Table 2 and Fig. 1, and new fixed-model engineering comparisons, use seed 11 and retain that narrower training-replication scope.')
methods=methods.replace('Dates are synchronized across methods.', 'Intervals are pointwise and are not simultaneous confidence bands or adjusted for multiple comparisons. Dates are synchronized across methods.')
methods=methods.replace('This tests whether placing the correction in a separately named PV output is necessary.', 'This tests whether placing the correction in a separately named PV output is necessary. A revision audit found negative nighttime outputs in the unrestricted signed candidate, especially after cost calibration. The primary direct-net comparison consequently projects net demand to nonnegative values in the same fixed nighttime slots used by the PV support rule; the 24-offset calibration is refitted with that projection in training, validation and deployment. The underlying supervised network is unchanged. The unrestricted signed results remain in the Supplement. This support correction followed a revision diagnostic and is not presented as an untouched confirmatory design.')
methods=methods.replace('Limited power-factor and impedance brackets test physical-assumption sensitivity.', 'Gross-demand power factors of 0.90, 0.95 and 1.00 bracket the modeled reactive demand; 0.95 is the reference [L42]. Line resistance and reactance are jointly scaled by 0.90 or 1.10 in separate sensitivity cases, with transformer parameters unchanged. These interpretable brackets test sensitivity rather than estimating the unknown physical network.')
methods += '''

2.7. Operational transfers, protection and mechanism

The continuous-state variant removes the daily terminal equality and credits a fixed inventory value V(e)=λe−ρ(e−5)², with λ=(lowest purchase price+κ)/0.95 and ρ=0.01 AUD/kWh². Each controller still optimizes the next 24 hours. Test states carry across identical clean evaluation segments, initialized at 5 kWh at each segment boundary. This offline quality rule defines observable evaluation episodes; it is not an operational reset triggered by future measurement values. Newly matched learning uses two consecutive daily controllers, passing the first end state into the second, on 4,088 training and 1,021 validation anchors. It is a two-day differentiable training rollout, not 48-hour perfect foresight or full-year backpropagation. The realized settlement-plus-wear total is reported both before and after the boundary correction V(e_start)−V(e_end). The fixed terminal value approximates remaining inventory and is not an estimated future revenue.

Wear prices of 0, 0.01 and 0.04 AUD per throughput kWh bracket the reference. Throughput-based degradation costing has precedent [L43], but these values are declared accounting sensitivities rather than cell-calibrated aging estimates. For each value we distinguish repricing unchanged actions, reoptimizing with frozen signals and reoptimizing after matched retraining. This prevents an accounting decomposition from being interpreted as a new operational policy.

A separate prospective protection scenario imposes a 3 kW per-site export limit. Ausgrid's current connection guidance describes fixed-export options associated with changes from late 2026 [L41]; we do not apply that policy retrospectively as a compliance standard for 2012–2013. Given a previously planned battery action, PV is curtailed only as needed to meet the site limit, and the lost export income is included in actual retail settlement. All controllers receive the same rule. This tests a common post-scheduling protection layer, rather than matched retraining of every learner with an export-constrained optimizer. All three fixed panels are retained because the rule may bind very differently across capacity distributions.

For mechanism, we prescribe the first jointly clean date in each season at 02:00, 12:00, 18:00 and 22:00, plus the nearest exogenous gross-load-minus-PV samples to its fifth, fiftieth and ninety-fifth percentiles. At these 19 operating points, centered 0.10 kW/kvar perturbations estimate the AC Jacobians Sᴾ and Sᑫ of continuous nodal voltage with respect to demand-positive active and reactive injections. Steps of 0.05 check sensitivity stability. Actual load and PV are unchanged between methods, so ΔP=Δc−Δd and ΔQ=0 under unity-power-factor battery operation. Full AC replay evaluates Δv against SᴾΔP+SᑫΔQ. A complete daily signal/action/phase-voltage example uses the first date in this prescription, rather than the largest favorable effect. Neither this local approximation nor the binary screening metric establishes dynamic response or real-feeder causation.

2.8. Frozen transfer to a separate public dataset

StoreNet provides direct consumption and generation power records for an Irish energy community [L40]. We inspect all 20 household files and retain ten households with verified PV production. The downloaded power pipeline supplies minute-grid records; its missing values remain missing. We aggregate only complete half-hours and retain target days with complete preceding seven-day histories. The result is 2,224 paired household-days in 2020. The interpolated cumulative-energy files are not used. We simulate the study battery from gross consumption and production; Irish battery telemetry and a controlled-load circuit are not reconstructed.

Documentation gives differing nominal PV ranges. Therefore, a 2.2 kWp normalization reference is fixed before external outcomes, and 2.0 and 2.4 kWp are fully reported sensitivities, not verified household capacities or outcome-selected scales. Original Australian prices and source-clock calendar inputs are retained without hemisphere adjustment. No external target data fit weights, offsets or hyperparameters. The primary time-of-use checkpoints and analysis files are hashed before evaluation and verified unchanged. Six original flat-price checkpoints were inadvertently omitted from that initial manifest; their hashes and original timestamps are documented in an explicitly post-run addendum. We therefore give the flat group secondary transfer status, without retrospectively claiming a complete prospective freeze. External cost transfer does not validate Ausgrid household-to-feeder assignments or represent actual Irish bills.
'''
p0=nc('five_conditions_seed11')
stats=p0['outcomes'];scale=read('network_system_scale.json')['panels'][0]
results=f'''3. Results

3.1. The incremental benefit is small relative to practical alternatives

Expanded time-of-use comparisons include 108,641 paired GC/PV household-days from all 299 eligible households; 107,713 of these also support full-cost settlement including CL. DFL reduces paired operating cost by {money(-d['micro_mean_difference'])} cents per household-day relative to continued MSE (95% calendar-block interval for DFL minus MSE, {interval(d['micro_calendar_block95'])} cents; Fig. 1a). Household-average weighting gives a nearly identical {money(-d['macro_mean_difference'])}-cent reduction. Three-offset calibration recovers {100*cal['micro_mean_difference']/d['micro_mean_difference']:.1f}% of the mean gain, leaving an additional {money(cal['micro_mean_difference']-d['micro_mean_difference'])} cents for DFL. The 12-offset seasonal extension supplies no clear time-of-use gain over three offsets. Direct net-load prediction and its 24-offset calibration have higher realized costs in this implementation; this unsuccessful baseline does not establish that a separate PV representation is necessary.

Scenario control yields a {money(-saa['micro_mean_difference'])}-cent reduction relative to continued MSE and a further {money(-sd['micro_mean_difference'])} cents relative to DFL ({interval(sd['micro_calendar_block95'])} cents for scenario minus DFL). It also beats DFL in all four fixed feeder panels. Scenario control is therefore a substantive practical comparator. In the first feeder panel, DFL closes approximately 1.7% of the continued-MSE to perfect-information cost gap under a common seed and mask. That fraction measures scale, not the share of an otherwise attainable improvement. The three-seed, nine main deployment-cell results remain consistent with a modest DFL increment: approximately 0.787–1.236 cents per battery-owner day. Fixed-seed engineering extensions are kept separate from those training-replicated estimates.

Private gains are not universal (Fig. 1b). Under time-of-use prices, 96.7% of households have lower mean DFL cost, compared with 92.6% for calibration and 91.3% for scenario control. The largest household mean increases are 13.42, 2.41 and 19.24 cents, respectively, over their observed valid days. A favorable population mean thus coexists with a material adverse tail. These empirical household summaries do not estimate adoption welfare or guarantee benefits to a new customer.

The time-of-use DFL gain separates into 0.495 cents of retail settlement and 0.636 cents of throughput-proxy cost (Fig. 1c); the latter supplies 56.3% of the total. Calibration's retail term increases slightly while its throughput term falls. Flat-price results have a different mechanism: DFL reduces retail settlement by 2.322 cents while increasing the wear term by 1.105 cents, giving a net 1.216-cent saving. Scenario control lowers flat-price operating cost by 4.725 cents relative to continued MSE. Reduced throughput is consequently a condition-dependent accounting outcome, rather than a universal battery-life result.

3.2. Computational overhead is measurable but not a scheduling bottleneck

Incremental matched DFL training takes 385.6 s, compared with 21.8 s for continued MSE and 87.3 s for three-offset calibration. The scenario bank requires no iterative task-specific learning. Deterministic schedules take about 1.5 ms per household, versus 9.3 ms for 20 scenarios; all are small on a daily control timescale (Table 3). These timings include validation selection where appropriate and exclude shared supervised pretraining. Peak process memory includes loaded data and libraries. Concurrent unrelated work prevents interpreting wall-time multiples as hardware-independent speed ratios. DFL's maintenance distinction is the need to preserve and test controller gradients and refit a coupled task signal after material input or objective changes. This is a concrete engineering cost, but the experiment does not show that scenario scheduling is computationally impractical.

3.3. Voltage frequency, magnitude and thermal loading support different conclusions

At a 1.050 pu source on the first 55-household panel, DFL reduces overvoltage exposure from 18.751% to 17.901% and undervoltage from 0.02577% to 0.02318%, relative to continued MSE. The combined change is {stats['daily_voltage_pct']['delta']['mean']:.3f} percentage points (Fig. 2c). Zero-inclusive excursion falls from 0.0005914 to 0.0005671 pu. However, conditional overvoltage magnitude increases slightly, from 0.0031444 to 0.0031594 pu. Fewer observed events are therefore not equivalent to milder remaining events (Fig. 2d). The 99th-percentile voltage moves from 1.058341 to 1.058259 pu and the maximum from 1.071964 to 1.071583 pu. The largest exposure location and the largest instantaneous voltage need not be the same node; their individual summaries and continuous episode lengths are retained in Supplementary Table S4.

Source settings materially change the problem. At 1.025 pu, neither method exceeds 1.05 pu and the combined reduction is only 0.00848 percentage points, entirely from reduced undervoltage. At 1.000 pu, undervoltage falls from 1.4598% to 1.3588%, while its conditional magnitude rises from 0.0133455 to 0.0134594 pu. Wide-band samples below 0.90 pu remain at 0.04393% and 0.04151%, respectively; they have not disappeared. At 1.025 pu that wide-band underexposure is 0.001038% for both methods. The two SimBench cases have no 0.95–1.05 pu events for either method, making conditional excursion undefined rather than zero.

The complete threshold curves expose this dependence (Fig. 2a,b). At the reference source, 9.64% of continued-MSE samples lie within ±0.001 pu of the upper screening limit. Small continuous shifts can consequently move many binary classifications. DFL's modeled exposure reduction is informative for that benchmark, but it does not prove a substantial compliance improvement on an unknown field feeder. Power-factor and impedance brackets retain a combined reduction of approximately 0.734–1.083 percentage points; ten fixed mappings retain 0.667–0.965 points. Those checks establish stability within this constructed high-source case, while the lower-source and alternative-topology results delimit its usefulness.

The reference mean daily import peak is {stats['daily_import_peak_kw']['baseline_mean']:.2f} kW, reduced by {abs(stats['daily_import_peak_kw']['delta']['mean']):.2f} kW ({abs(stats['daily_import_peak_kw']['relative_delta_pct']):.2f}%). Losses fall by {abs(stats['daily_loss_kwh']['delta']['mean']):.3f} kWh/day ({abs(stats['daily_loss_kwh']['relative_delta_pct']):.2f}%). Export peak increases by {stats['daily_export_peak_kw']['delta']['mean']:.3f} kW ({stats['daily_export_peak_kw']['relative_delta_pct']:.2f}%). These movements cannot be summarized as uniform grid improvement. The unchanged 800 kVA transformer reaches 25.29% aggregate loading, with a maximum phase loading of 36.44%; the primary case is not transformer thermal congestion (Table 1). Conversely, the constructed 160 kVA rural SimBench case reaches 119.83% loading and exceeds nominal loading in 0.761% of valid half-hours, despite no narrow-band voltage events. Voltage safety and thermal loading are separate criteria.

Scenario control has lower costs, import peaks and losses than DFL in every fixed panel. Its overvoltage ranking changes across panels: DFL minus scenario exposure is about −0.343, +1.138, +0.132 and −0.207 percentage points for the three fixed panels and the held-out panel. There is no stable voltage premium that offsets DFL's higher mean private cost. Calibration and direct-net alternatives also produce different cost and network rankings. A network requirement therefore needs to be evaluated explicitly, rather than inferred from private objective alignment.

3.4. The mechanism is a timing adjustment transmitted through phase-coupled injections

On the first prescribed date, the task signal changes during daylight, yet the resulting battery differences also appear at off-peak boundaries (Fig. 3a,b). Because true gross demand and PV are held fixed, the injection difference is exactly the difference in discharge minus charge. The phase-resolved voltage response changes sign over the day and differs substantially between phases (Fig. 3c). On that date at 22:00, the aggregate demand difference is −2.417 kW and the mean voltage change is +0.000734 pu, with a maximum absolute receiving-node change of 0.002064 pu. The dominant sender and receiving location need not coincide; cross-phase effects also appear in the local contribution matrices.

Across the 19 prescribed operating points, the largest absolute discrepancy between local linear voltage prediction and full AC change is 5.01×10⁻⁶ pu (Fig. 3d). Halving the perturbation changes the predicted voltage difference by at most 6.62×10⁻⁸ pu. Eighteen cases have relative L2 discrepancy at most 0.216%; the summer 02:00 case has essentially zero action change and a voltage difference near 10⁻⁹ pu, so a relative error near one is a near-zero denominator effect and is retained. This explains modeled transmission of small action changes, without differentiating an exceedance indicator or validating unobserved network parameters.

The earlier shared-signal decomposition assigns approximately 90% of the first-panel private gain to its common component. That counterfactual uses test-derived corrections and remains diagnostic. The deployable three- and twelve-offset tests are the direct competing explanation: a simple trained correction recovers a substantial fraction, but not all, of the DFL gain. The mechanism supports a modest timing correction; it does not establish superior extraction of physical PV information.

3.5. Controller conditions distinguish transport from adaptation

Figure 4 separates changes to a frozen signal from matched learning in the changed environment. Replacing the reference load input with previous-day persistence changes frozen DFL minus MSE cost to +0.312 cents per day, with an interval spanning zero. Matching both learners to persistence restores a 1.475-cent DFL saving. The stronger deployable load mixture gives a modest validation RMSE improvement, from 0.5473 to 0.5423 kW; a single neural load model is inferior and remains reported. Neither that small error improvement nor the privileged true-load diagnostic should be treated as evidence that the task signal is a transferable physical PV forecast.

Under continuous SOC, matched DFL retains a 1.313-cent daily benefit. Raw operating and inventory-adjusted contrasts are nearly identical, and average daily terminal energy is about 5.22 kWh for both methods. The difference is consequently not explained by exhausting the terminal stock. The precise frozen-controller transfer and wear sensitivities are reported in Fig. 4 and Supplementary Table S6. Separate action repricing and policy reoptimization are retained even when they happen to agree. At zero wear, repricing and frozen-signal reoptimization both give a 0.495-cent benefit, while matched retraining gives 0.792 cents. Thus the gain is not wholly created by throughput pricing, although its reference magnitude depends substantially on that proxy.

A common 3 kW export protection layer retains DFL's matched private and voltage-frequency benefit on the three fixed panels. Its physical importance is heterogeneous: continued-MSE curtailment is approximately 0.0006, 10.676 and 0.090 kWh per feeder-day across those panels. The second panel loses about 1.553 cents of export income per household-day, compared with 1.584 cents under DFL. After repricing this protection, DFL minus continued-MSE costs are −1.123, −1.267 and −1.125 cents per day, and overvoltage changes are −0.850, −1.254 and −1.044 percentage points. This is evidence of survival under that common protection layer, not a substitute for voltage-responsive inverter dynamics or export-constrained retraining.

3.6. Separate data and cohort checks define portability

Frozen time-of-use transfer to the ten StoreNet PV households gives a three-seed mean DFL reduction of 1.252 cents per paired day at the fixed 2.2 kWp reference (95% DFL-minus-MSE interval, −1.741 to −0.767 cents). The 2.0 and 2.4 reference scales yield 1.573 and 0.803 cents, respectively. All scales remain reported. One seed's interval crosses zero; the evidence does not establish uniformly positive transfer across fitted models. Flat-price mean cost instead increases by about 0.122 cents at 2.2 kWp, with an interval of −0.194 to +0.458 cents. Secondary flat transfer is inconclusive, rather than a confirmed saving. These outcomes concern original Australian prices applied to a separate dataset, not Irish tariffs or independently measured feeder voltages.

The size- and load/PV-matched postcode check uses 27 households in each cohort, the same 27 electrical positions and 160 common clean dates. The difference between grouped and dispersed DFL-minus-MSE cost gaps is −0.070 cents per day (interval −0.286 to +0.118); the overvoltage-gap difference is +0.147 percentage points (−0.024 to +0.310). Thus the check supplies no clear directional advantage in either outcome. The grouped cohort has a 0.218 kW less favorable import-peak reduction. These are differences between constructed matched cohorts, not an identified geographic effect.

The private expansion avoids discarding usable households because another site is missing. The feeder masks remain selective: the first panel has no jointly clean dates in July 2012 or March 2013, and the second has only 129 of 365 test dates. Monthly counts and retained-demand/PV descriptions in Supplementary Table S1 identify that limitation explicitly. Temporal confidence intervals conditional on those masks do not create the omitted seasons or a new test year.
'''
discussion='''4. Discussion

4.1. An engineering selection rule from the combined evidence

The results change the question from whether a differentiable learner can obtain a statistically stable saving to whether that saving warrants a particular implementation. For an existing deterministic day-ahead controller, three trainable offsets provide an inexpensive structural correction with about half of the observed time-of-use DFL benefit. DFL adds roughly half a cent per household-day over that alternative. This increment may be relevant when the differentiable training infrastructure already exists and deterministic deployment is required, but the study does not estimate its break-even software or service cost. It is small enough that an engineering case should include maintenance, customer harm and operational requirements.

When 20 residual scenarios are acceptable, scenario control has the lower modeled mean cost under both tariffs. Its additional solve time is only several milliseconds, and the experiment reveals no daily scheduling bottleneck. The current evidence therefore favors considering uncertainty representation before deploying a task-trained deterministic signal solely for private cost savings. This conclusion is limited to the tested residual construction, price regimes and common battery. It is not a proof of universal scenario dominance, and it does not substitute for modern probabilistic forecasting evaluated under a wider set of objectives [L21,L22,L31,L32].

Network outcomes do not reverse that choice consistently. DFL reduces reference exposure relative to matched statistical training, but source voltage and topology determine whether a voltage problem is present and which direction dominates. The same DFL action may lower import losses yet increase export peak. Scenario control has lower import peaks and losses throughout the fixed-panel comparison, while voltage ordering changes sign. These results support evaluating network constraints or services directly when they are deployment requirements. Recent phase-balancing, stochastic-flexibility and grid-aware controllers already pursue such system objectives [L36,L37,L39]. The contribution here is to expose the bounded AC consequences of changing a private learner's objective under otherwise fixed information, rather than to replace coordinated management.

4.2. What the task signal represents

The learner modifies the optimizer's net-demand input. With a frozen demand forecaster, placing that correction in a nonnegative PV-shaped output is a modeling convention. The shift may compensate a combination of load error, PV error and the asymmetric operating objective. Cost gains cannot identify the source of the compensation. Matched retraining after persistence substitution establishes adaptation of a coupled learning-control system; the poor frozen transport establishes that its original output should not be passed to another input pipeline as if it were a calibrated conditional physical forecast.

Direct net-load prediction is conceptually consistent with that observation. Its weaker measured error and operating performance here prevents a strong empirical architecture comparison. Adding 24 cost-calibration parameters improves that candidate but does not remove its cost deficit, while its network ranking may be favorable. The evidence therefore leaves architecture necessity unresolved and does not use an unsuccessful baseline to justify a PV-specific high-dimensional correction. The low-dimensional calibration test is stronger evidence about practical complexity because it reuses the competitive common forecasting backbone.

4.3. Operational scope and unresolved uncertainty

Continuous-state replay and a sourced export limit address consequential boundaries of the reference controller. They show that the modeled incremental saving is not solely a daily-terminal or unconstrained-export artifact. The terminal value remains fixed, actions are open-loop within a day, and the export intervention is an identical protection layer after scheduling. Neither experiment reproduces a fully integrated inverter/controller with measured state error, degradation, network feedback and faults. Table 4 states supported conclusions and the stronger claims that would require different evidence.

The main transformer is lightly loaded and the upper screening limit lies near its retained source voltage. The broad voltage curves, near-threshold density and conditional severity show why a percentage-point reduction alone overstates practical importance. Conversely, the smaller rural transformer can be overloaded without screening-band voltage excursions. A field engineering assessment would require simultaneous voltage and thermal measurements and actual connectivity. Additional random assignments within the present data cannot supply those observations.

The independent StoreNet transfer strengthens one private-cost conclusion across datasets, while revealing a flat-price boundary and training-seed variation. Its normalization references are uncertain and its source calendar is deliberately unadapted. There is no claim that it validates future Australian weather, real Irish bills or the constructed feeder. Ausgrid evaluation remains informed by a test-triggered redesign, and the revision comparisons are recorded adaptations, not preregistered confirmation. Claims about economic returns, lifetime, transient protection or national adoption require observations not contained in these records. Concentrating those boundaries clarifies the useful conclusion: task training adds a modest conditional deterministic-control capability, while simpler calibration and scenario control remain competitive engineering choices.

5. Conclusion

Matched decision-focused training changes residential battery actions and their AC consequences, but the resulting private increment is small. A three-offset calibration captures a substantial share, and a feasible residual-scenario controller supplies lower mean private cost. Source voltage determines whether the observed voltage-frequency improvement addresses a present screening problem, and remaining-event severity need not improve. Deployable input changes distinguish frozen-signal transport from matched adaptation; continuous SOC and external time-of-use transfer retain a cost benefit under explicitly modeled boundaries. Engineering selection should therefore be based on the required information, controller boundary and private/network outcomes, rather than on forecast RMSE or the availability of a differentiable optimizer alone.

Data and code availability

Ausgrid source records are publicly distributed under their stated license [L30], and StoreNet records and documentation are available through their public collection [L40]. The European benchmark and SimBench networks are publicly described [L19,L23]. The accompanying reproduction package contains source-data acquisition instructions, cohort/date masks, model checkpoints, saved dispatch, derived figure data and executable table/figure and consistency checks. A public archival identifier has not yet been assigned. Local artifact availability is not represented as a public repository or DOI.

Declaration of generative AI use

Generative AI agents assisted literature discovery, research-design revision, Python implementation, computational analysis, figure construction and manuscript drafting. Assistance included code and quantitative analysis, beyond language editing. Source access limits are recorded, and key settlement calculations, masks, state transitions, optimization gradients and AC approximation claims were checked against saved outputs and independent computations. These checks do not replace human authorship review. No final human approval or authorship responsibility is asserted by an automated system; human authors must review the submitted work and complete the journal's declaration under their own responsibility.

Competing interests and funding

No competing-interest or funding status is inferred from the computational records. Human authors must supply the applicable declarations before submission.
'''
methods=methods.replace('We aggregate only complete half-hours and retain target days with complete preceding seven-day histories.', 'We retain half-hours with at least 27 valid minute observations out of 30 in each required power channel and average the available observations without interpolation. Target days require all 48 retained half-hours and complete preceding seven-day retained histories.')
results=results.replace('The precise frozen-controller transfer and wear sensitivities are reported in Fig. 4 and Supplementary Table S6.', 'Frozen continuous-controller transport gives a 1.135-cent inventory-adjusted saving, compared with 1.313 cents after matched two-day training. The stronger load mixture gives savings of 1.194 cents under frozen transport and 1.235 cents after matched retraining. The complete intervals and cohort estimates are reported in Fig. 4 and Supplementary Table S6.')
results=results.replace('Thus the gain is not wholly created by throughput pricing, although its reference magnitude depends substantially on that proxy.', f"At wear prices of 0.01 and 0.04, frozen-signal reoptimization gives {money(-ctrl['wear']['0.01']['frozen_signals_reoptimized']['all299']['micro_mean_difference_aud'])} and {money(-ctrl['wear']['0.04']['frozen_signals_reoptimized']['all299']['micro_mean_difference_aud'])} cents of saving, while matched retraining gives {money(-ctrl['wear']['0.01']['matched_signals_reoptimized']['all299']['micro_mean_difference_aud'])} and {money(-ctrl['wear']['0.04']['matched_signals_reoptimized']['all299']['micro_mean_difference_aud'])} cents. Thus the gain is not wholly created by throughput pricing, although its reference magnitude depends substantially on that proxy.")
results=results.replace('A common 3 kW export protection layer', 'The persistence case supplies a direct private/network counterexample. Under matched retraining, the first and held-out panels save approximately 1.625 and 1.580 cents per owner-day, yet overvoltage exposure increases by 0.373 percentage points (95% interval 0.177 to 0.576) and 0.606 points (0.465 to 0.750); mean daily import peaks increase by about 2.51 kW in both panels. Continuous-state matched retraining instead reduces overexposure by approximately 1.136 and 1.040 points. Private gains under input adaptation therefore do not provide a stable proxy for network value.\n\nA common 3 kW export protection layer')
discussion=discussion.replace('Network outcomes do not reverse that choice consistently.', 'Network outcomes do not reverse that choice consistently. The matched-persistence counterexample is particularly consequential: private saving improves while overvoltage and import peak worsen on both evaluated panels. Network consequences must therefore be rechecked after retraining even when private validation selects a better operating model.')
discussion=discussion.replace('Table 4 states supported conclusions','Table 5 states supported conclusions')
base=[{'type':'title','text':title},{'type':'heading','text':'Abstract'},{'type':'paragraph','text':abstract},
 {'type':'paragraph','text':'Keywords: residential battery; decision-focused learning; scenario optimization; voltage exposure; AC power flow; public data'}]+blocks(intro)+blocks(methods)
# Keep the primary system context compact and denominators explicit.
sysrows=[]
for p in read('network_system_scale.json')['panels']:
 sysrows.append([f"{'Held-out' if p['panel']==3 else 'Panel '+str(p['panel']+1)}",str(p['n_clean_days']),f"{p['pv_capacity_kwp_distribution']['median']:.2f}",f"{p['household_mean_daily_gross_demand_kwh']['median']:.2f}",f"{p['battery_capacity_to_household_daily_demand_ratio']['median']:.2f}",f"{p['total_pv_kwp_to_transformer_kva']*100:.2f}",f"{p['reference_observed_max_transformer_loading_pct']:.2f}"])
base.append(table('Table 1. Scale of the constructed European LV panels.', ['Panel','Clean days','PV median (kWp)','Daily demand median (kWh)','Battery / demand','PV / 800 kVA (%)','Max loading (%)'],sysrows,'55 households per panel; 10 kWh and 3 kW batteries at full adoption. Demand includes GC and CL. Loading refers to continued MSE, seed 11, full time-of-use adoption. Battery/demand is the median of household capacity-to-mean-daily-gross-energy ratios, not a ratio of panel medians or a duration. Source voltage 1.050 pu.'))
rs=blocks(results)
for b in rs:
 base.append(b)
 if b['text'].startswith('The time-of-use DFL gain separates'):
  rows=[]
  for key,label in [('msecont','Continued MSE'),('calibrated3','3-offset calibration'),('dfl','DFL'),('stochastic20','20 scenarios')]:
   z=np.load(R/'dispatch'/f'{key}_tou_seed11_expanded.npz');mask=z['clean_day'];assert mask.sum()==107713
   cost=float(z['bill_aud'][mask].mean())
   # Full cost less same-mask throughput proxy is a same-sample retail identity.
   tp=float(z['energy_throughput_kwh'][mask].mean());retail=float(z['retail_bill_aud'][mask].mean());assert abs(cost-retail-.02*tp)<1e-8
   q=pair('tou',key) if key!='msecont' else None
   rows.append([label,f'{cost:.5f}',f'{retail:.5f}',f'{tp:.3f}', '0' if q is None else money(q['micro_mean_difference']), 'Reference' if q is None else interval(q['micro_calendar_block95'])])
  base.append(table('Table 2. Matched private costs and practical alternatives.', ['Method','Full cost (AUD/day)','Retail (AUD/day)','Throughput (kWh/day)','Paired Δ (cents/day)','95% interval (cents/day)'],rows,'Absolute full cost, retail and throughput all use the same 107,713 CL-valid household-days; full cost = retail + 0.02 × throughput. Paired changes use all 108,641 GC/PV-valid days, for which the identical CL charge cancels. 299 households, seed 11, time-of-use tariff; Δ is method minus continued MSE. Figure 1 retains all seven implemented alternatives.'))
  base.append(figure(1,'economics','Cost, practical alternatives and household distributions.','a, Paired operating-cost changes and 95% seven-day calendar-block intervals. b, Empirical CDF of household mean cost differences, retaining adverse tails. c, Mean retail and throughput-proxy components. 299 households and 108,641 paired days; seed 11, time-of-use prices. Negative costs favor the alternative.'))
 if b['text'].startswith('Incremental matched DFL training'):
  rows=[]
  for key,label in [('msecont','Continued MSE'),('calibrated3','3-offset calibration'),('dfl','DFL'),('stochastic20','20 scenarios')]:
   q=res['rows'][key];rows.append([label,f"{q['training_seconds_including_validation_selection']:.2f}",f"{q['mean_qp_ms']:.2f} / {q['p95_qp_ms']:.2f}",f"{q['inference_peak_rss_mb']:.0f}",q['update_requirement']])
  base.append(table('Table 3. Incremental resource and maintenance comparison.', ['Method','Learning (s)','Mean / p95 solve (ms)','Replay RSS (MB)','Update requirement'],rows,'1,024 fixed validation pairs, 20 warm-ups and three repetitions; scheduling benchmarks executed serially in single-thread subprocesses, with unrelated revision tasks concurrent. Solve time includes QP updating and solving, and excludes forecast features and prediction inference. Learning includes each method’s own validation selection; common supervised fitting is excluded. Scenario learning column times residual extraction, not iterative fitting. Replay RSS is peak process working set including data and libraries; training RSS is reported separately in Table S3. Absolute times are hardware/environment dependent.'))
 if b['text'].startswith('The complete threshold curves'):
  base.append(figure(2,'voltage','Voltage changes across source settings and network models.','a,b, Complete prescribed upper and lower threshold curves. c, Matched over/under-exposure changes at fixed 1.05/0.95 pu screening limits, with 95% calendar-block intervals. d, Pooled magnitude conditional on an event; absent points denote undefined outcomes when no event occurs. Continued MSE and DFL, seed 11, panel 1 and full time-of-use adoption.'))
 if b['text'].startswith('The earlier shared-signal decomposition'):
  base.append(figure(3,'mechanism','Task signal to action, injection and continuous voltage.','a–c, First prescribed clean date, 24 August 2012; no selection by effect magnitude. Charging/discharging changes are summed over 55 households, and net injection change equals discharge minus charge under identical truth. Voltage curves show phase means, not worst nodes. d, Full AC versus local linear voltage changes at all 19 prescribed points and all 55 receiving locations; the dashed line is identity. DFL minus continued MSE, seed 11.'))
 if b['text'].startswith('Scenario control has lower costs, import peaks'):
  records=read('network_diagnostics/scenarios.json')['records'];rows=[]
  for key,label in [('msecont','Continued MSE'),('calibrated','3 offsets'),('dfl','DFL'),('stochastic','20 scenarios')]:
   q=next(x for x in records if x['metadata']['objective']==key and x['metadata']['seed']==11 and x['metadata']['panel']==0 and x['metadata']['battery_count']==55 and x['metadata']['tariff_mix']=='all_tou' and x['metadata']['comparison_group'] in (None,'original_physical') and x['metadata']['parameters']['network']=='eulv' and x['metadata']['parameters']['source_pu']==1.05 and x['metadata']['parameters'].get('mapping_seed') is None and x['metadata']['parameters'].get('power_factor',.95)==.95 and x['metadata']['parameters'].get('impedance_scale',1.0)==1.0 and x['metadata']['parameters'].get('export_limit_kw') is None and x['metadata']['parameters'].get('export_limit_kw') is None)
   v=q['voltage'];f=q['flow'];rows.append([label,f"{f['daily_operating_cost_aud']['mean']:.5f}",f"{v['over_pct']:.3f}",f"{v['under_pct']:.4f}",f"{f['daily_import_peak_kw']['mean']:.2f}",f"{f['daily_export_peak_kw']['mean']:.2f}",f"{f['daily_loss_kwh']['mean']:.3f}"])
  base.append(table('Table 4. Joint private and network outcomes under common feeder conditions.',['Method','Cost (AUD/owner-day)','Over (%)','Under (%)','Import peak (kW)','Export peak (kW)','Loss (kWh/day)'],rows,'Panel 1, 55 time-of-use owners, 219 identical clean dates, seed 11, 1.050 pu source, reference PF and impedances. Private costs include CL and the throughput proxy. Voltage percentages pool customer half-hours; peaks and losses are means of daily outcomes. This common-feeder subset differs from Table 2’s expanded private sample; Table 3 measures computational resources.'))
 if b['text'].startswith('Under continuous SOC'):
  base.append(figure(4,'boundaries','Input, controller, wear and external-transfer boundaries.','a, Deployable load-input changes. b, Continuous-SOC raw and inventory-adjusted costs. c, Wear-price sensitivities distinguish unchanged-action repricing, frozen-signal reoptimization and matched retraining. d, All predeclared StoreNet normalization references under both tariffs, with three-seed averaging. Points and intervals are paired mean differences and 95% calendar-block intervals. Negative values favor DFL; frozen transport and matched adaptation estimate different questions.'))
base+=blocks(discussion)
boundaryrows=[['Private cost','Small matched time-of-use benefit; calibration captures about half; tested scenarios lower mean cost.','No universal method ranking, profitable deployment or customer-level guarantee.'],['Voltage / thermal','Exposure depends on source and topology; frequency and conditional magnitude differ.','No observed field compliance, transient response or thermal-congestion benefit in the main 800 kVA case.'],['Signal transport','Deployable persistence transport can lose the gain; matching can recover it.','No improved physical PV information or architecture necessity.'],['SOC / wear / protection','Benefit survives specified inventory and protection models; wear affects magnitude.','No measured lifetime extension, full aging economics or integrated inverter validation.'],['Independent data','Frozen time-of-use transfer to ten external households; all capacity references reported.','Flat transfer inconclusive; no real Irish bills, future-year or feeder validation.']]
idx=next(i for i,b in enumerate(base) if b.get('text','').startswith('The main transformer is lightly')) if any(b.get('text','').startswith('The main transformer is lightly') for b in base) else len(base)
base.insert(idx,table('Table 5. Supported conclusions and stronger claims requiring different evidence.',['Domain','Supported by this study','Boundary'],boundaryrows,'The article is a computational application and validation study. Numerical consistency, uncertainty conditional on observations and field-model validity are distinct.'))
# References are numbered on first appearance; neither abstract-only reading nor unresolved author declarations are hidden.
refs={}
for p in [ROOT/'manuscript/references_verified.txt',R/'research/references_revision.txt']:
 for match in re.finditer(r'\[(L\d+)\]\s*(.*?)(?=\n\s*\[L\d+\]|\Z)',p.read_text(encoding='utf-8'),re.S):refs[match.group(1)]=' '.join(match.group(2).split())
used=[]
def remap(text):
 def f(match):
  keys=re.findall(r'L\d+',match.group())
  for k in keys:
   if k not in refs:raise KeyError(k)
   if k not in used:used.append(k)
  return '['+', '.join(str(used.index(k)+1) for k in keys)+']'
 return re.sub(r'\[L\d+(?:\s*,\s*L\d+)*\]',f,text)
for b in base:
 for k in ['text','caption','note']:
  if k in b:b[k]=remap(b[k])
base.append({'type':'heading','text':'References'})
for i,k in enumerate(used,1):base.append({'type':'reference','text':f'[{i}] {refs[k]}'})
out={'title':title,'target_journal':'Electric Power Systems Research','blocks':base,'reference_keys':used,'abstract_words':len(abstract.split())}
(M/'article_blocks.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
def plaintext(bs):
 eq={'[[EQ_BATTERY]]':'e_t = e_(t−1) + Δ(η c_t − d_t/η); 0 ≤ c_t,d_t ≤ 3; 1 ≤ e_t ≤ 9; e_0 = e_48 = 5. (1)', '[[EQ_OBJECTIVE]]':'J_hat = Δ Σ_t [p_buy,t max(g_hat,t,0) + p_sell,t min(g_hat,t,0) + κ(c_t+d_t)] + ε R(c,d,e). (2)', '[[EQ_SELECTION]]':'R(c,d,e) = Σ_t [(c_t/3)^2 + (d_t/3)^2 + (e_t/10)^2]. (3)', '[[EQ_DFL]]':'L_DFL(θ) = (1/N) Σ_i C_i[A_ε(l_hat,i − f_θ(x_i))]. (4)'}
 return '\n\n'.join(eq.get(b.get('text',''),b.get('text',b.get('caption','')))+ ('\n'+' | '.join(b['headers'])+'\n'+'\n'.join(' | '.join(str(x) for x in row) for row in b['rows'])+'\n'+b['note'] if b['type']=='table' else ('\n'+b['note'] if b['type']=='figure' else '')) for b in bs)
(M/'article_full.txt').write_text(plaintext(base),encoding='utf-8')
(M/'numeric_claim_registry.json').write_text(json.dumps({'expanded_economics':eco,'control':ctrl,'network_summary_file':'network_revision_summary.json','reference_key_order':used},indent=2),encoding='utf-8')
print(json.dumps({'blocks':len(base),'references':len(used),'abstract_words':len(abstract.split()),'body_words':sum(len(b.get('text','').split()) for b in base if b['type']=='paragraph')}))
