"""Readable supplementary methods and complete predeclared comparison tables."""
from pathlib import Path
import json,numpy as np
ROOT=Path(__file__).resolve().parents[1];R=ROOT/'revision_20261009';M=R/'manuscript'
def read(p):return json.loads((R/p).read_text(encoding='utf-8'))
def fmt(x,d=3):return 'Undefined' if x is None or not np.isfinite(x) else f'{x:.{d}f}'
bs=[{'type':'title','text':'Supplementary methods and results'}, {'type':'paragraph','text':'Companion to: When does decision-focused learning add value to residential battery control? Private costs and AC feeder consequences.'}]
def h(text):bs.append({'type':'heading','text':text})
def p(text):bs.append({'type':'paragraph','text':text})
def tab(caption,headers,rows,note):bs.append({'type':'table','caption':caption,'headers':headers,'rows':rows,'note':note})
j=read('network_revision_summary.json');ctl=read('results/control_transfer_summary.json')
h('S1. Source chronology, coverage and sample formation')
p('The source-clock half-hours and data-quality indicators are retained. Nominal PV capacity is taken from information available before each target day, not estimated by outcome maximization. Known-household training has 132,200 days and validation 44,373; test evaluation has 88,609 known and 20,032 held-out GC/PV-valid days. The CL-valid absolute-cost sample is 107,713 days. Estimated measurements and required-channel gaps are excluded, and no missing meter record is synthesized. Feeder complete dates must satisfy every assigned household’s required channels. The expanded private comparison and joint feeder comparison thus answer different estimands.')
cov=j['calendar_coverage'];months=list(cov[0]['months']);rows=[]
for month in months:rows.append([month,str(cov[0]['months'][month]['calendar_days'])]+[str(x['months'][month]['clean_days']) for x in cov])
rows.append(['Total','365']+[str(x['clean_days']) for x in cov])
tab('Table S1a. Jointly clean dates by calendar month.',['Month','Calendar','Panel 1','Panel 2','Panel 3','Held-out'],rows,'Counts are actual evaluated dates, not bootstrap replicates. Panel 2 coverage is 35.3% of the calendar. Zero months remain in the calendar-axis resampling array.')
raw=np.load(ROOT/'datasets/ausgrid_source_clock_panel.npz');dates=raw['date'].astype(str);dh={d:i for i,d in enumerate(dates)};hh={int(h):i for i,h in enumerate(raw['household_id'])};records=read('network_diagnostics/scenarios.json')['records'];rows=[]
for pi in range(4):
 q=next(x for x in records if x['metadata']['objective']=='msecont' and x['metadata']['seed']==11 and x['metadata']['panel']==pi and x['metadata']['battery_count']==55 and x['metadata']['tariff_mix']=='all_tou' and x['metadata']['comparison_group'] in (None,'original_physical') and x['metadata']['parameters']['network']=='eulv' and x['metadata']['parameters']['source_pu']==1.05 and x['metadata']['parameters'].get('mapping_seed') is None and x['metadata']['parameters'].get('power_factor',.95)==.95 and x['metadata']['parameters'].get('impedance_scale',1.0)==1.0 and x['metadata']['parameters'].get('export_limit_kw') is None)
 z=np.load(R/'network_diagnostics'/(q['scenario_id']+'.npz'));hs=[hh[int(x)] for x in z['household_id']];ds=[dh[x] for x in z['date'].astype(str)];v=raw['power_kw'][hs][:,ds];clean=z['clean_day'];valid=raw['valid_feeder_day'][hs][:,ds]
 gross=(v[...,0]+v[...,1]).sum(axis=2)*.5;pv=v[...,2].sum(axis=2)*.5
 rows.append([str(pi+1) if pi<3 else 'Held-out',str(int(clean.sum())),fmt(gross[:,clean].mean(),2),fmt(pv[:,clean].mean(),2),str(int(valid.sum())),fmt(gross[valid].mean(),2),fmt(pv[valid].mean(),2)])
tab('Table S1b. Load and PV on retained feeder dates versus individually valid dates.',['Panel','Joint dates','Joint demand (kWh/day)','Joint PV (kWh/day)','Individual days','Individual demand','Individual PV'],rows,'Both descriptions use observed gross GC+CL and PV. Individually valid days need not support all-site AC replay and are not a missing-data correction. Main private GC/PV comparisons additionally allow CL cancellation.')
h('S2. Learning and baseline specifications')
p('The 774-input PV network uses 128/64 ReLU hidden units and 48 softplus outputs. Supervised configuration selection precedes three-seed initialization. DFL and continued MSE share 4,096 training pairs, 1,024 validation pairs, batch 32, four epochs, AdamW weight decay 10⁻⁴, gradient clipping at norm 1, and learning-rate candidates 10⁻⁴ and 3×10⁻⁵. Initial checkpoints are eligible; downstream validation cost chooses each arm’s checkpoint. All initialization, sampling and selection records are retained, including unsuccessful settings. Night restriction fixes 00:00–04:00 and 21:00–24:00 to zero. Its initial introduction followed an Ausgrid test diagnostic and is not represented as preregistration.')
p('Three-offset and twelve-offset calibration use bounds 0.25×tanh(parameter) in capacity-normalized units, three epochs of Adam at 0.03 and training batch 32. Calibration uses 2,048 known training and 2,048 validation examples. Validation chooses shrinkage in {0,0.25,0.5,0.75,1}. The seasonal variant crosses three fixed daytime windows with DJF/MAM/JJA/SON. Direct net-load prediction uses signed linear outputs, the same inputs, and full training/validation splits; two prespecified AdamW configurations are selected by validation MSE with at most 30 epochs and patience six. Six four-hour windows by four seasons give 24 cost-calibration parameters. An explicit support-matched nighttime projection and the unrestricted signed diagnostic are retained separately where available; revision chronology is disclosed in the main Methods.')
p('The stronger demand network has 256/128 hidden units and softplus outputs. Validation chooses the mixture of the original HGB and this network among weights 0,0.25,0.5,0.75,1; it selects 0.5. A previous-day profile is the persistence comparator. Residual scenarios use the original frozen forecast backbone and 20 joint load/PV daily residual paths from 147 clean validation dates. A deterministic donor policy supplies household-held-out residuals. Shared battery actions apply in every scenario; no oracle recourse, network coordination or test residual fitting is introduced.')
rows=[]
for t in ('tou','flat'):
 e=read(f'results/expanded_comparison_{t}_support_matched_baselines.json');c=e['cohorts']['all299'];ref=e['reference']
 signed=read(f'results/expanded_comparison_{t}_all_baselines.json')['cohorts']['all299']
 entries=[(name,v,c) for name,v in c['absolute'].items()]+[(name,v,signed) for name,v in signed['absolute'].items() if name.startswith(('net_mse_'+t,'net_calibrated24_'+t))]
 for name,v,cohort in entries:
  z=np.load(R/'dispatch'/(name+'.npz'));mask=z['clean_day'];tp=float(z['energy_throughput_kwh'][mask].mean());q=cohort['paired'].get(name+'__minus__'+ref)
  rows.append([t,name.split('_'+t)[0],fmt(v['mean_full_operating_cost'],5),fmt(v['mean_retail_only'],5),fmt(tp),fmt(100*q['micro_mean_difference']) if q else '0', 'Reference' if q is None else f"{fmt(q['micro_calendar_block95'][0]*100)} to {fmt(q['micro_calendar_block95'][1]*100)}"])
tab('Table S2. Complete all-household baseline comparison.',['Tariff','Method','Full cost','Retail','Throughput','Paired Δ (cents)','95% interval'],rows,'Cost and retail: AUD/day, same 107,713 CL-valid days; listed throughput is independently reaggregated on that same mask. Paired Δ uses 108,641 GC/PV days, identical CL charge cancels. Negative Δ favors the row method over continued MSE. Seed 11; unsuccessful candidates are retained.')
pm=read('results/revision_predictive_metrics.json')
p('Predictive metrics are diagnostic, not downstream selection criteria for task learning. The common and selected mixed demand validation RMSEs are 0.547316 and 0.542329 kW, respectively; the neural-only demand model has 0.5510 kW validation RMSE. On the 244 known households and 88,609 test household-days, the original unrestricted signed direct-net MSE has about 0.6253 kW test RMSE versus about 0.6184 kW for the separated MSE net input. These diagnostic values precede the support-matched revision and do not establish a stronger direct-net baseline or architecture necessity. Complete split and role metrics accompany the machine-readable reproduction records.')
h('S3. Resource conditions and numerical definitions')
p('Resource timings use 1,024 fixed validation pairs, 20 warmups and three serial method repeats, with one numerical thread per subprocess. Other revision calculations run concurrently. Windows CPU-clock granularity affects individual process-CPU measurements; both wall and CPU summaries are retained. Common original supervised fitting is excluded. Continued-MSE/DFL resource refits reproduce their original fitting protocol, while performance uses the original frozen models. All sample counts, validation procedures and memory scope are reported rather than treating different fitting procedures as equal-budget attribution tests.')
res=read('results/resource_comparison_tou.json');rows=[]
for k,v in res['rows'].items():rows.append([k,fmt(v['training_seconds_including_validation_selection'],2),fmt(v['mean_qp_ms']),fmt(v['p95_qp_ms']),fmt(v['mean_process_cpu_qp_ms']),fmt(v['inference_peak_rss_mb'],1),fmt(v.get('training_peak_rss_mb'),1)])
tab('Table S3. Full resource measurement.',['Method','Learn (s)','Mean wall (ms)','p95 wall (ms)','Mean CPU (ms)','Replay RSS (MB)','Learn RSS (MB)'],rows,'RSS includes interpreter, dependencies and loaded arrays. No memory claim for a hypothetical embedded deployment is inferred. SAA learning is residual extraction only.')
h('S4. Direction, severity, worst locations and event persistence')
rows=[]
for q in j['pooled_conditional_severity_five_conditions']:
 v=q['voltage'];zz=np.load(R/'network_diagnostics'/(q['scenario_id']+'.npz'));over=int(v['worst_over_node_index']);under=int(v['worst_under_node_index']);level=v['quantile_levels'];vals=v['quantiles'];q99=vals[level.index(.99)]
 worst=f"{over+1 if v['over_pct']>0 else 'Undefined'}/{under+1 if v['under_pct']>0 else 'Undefined'}"
 rows.append([q['network'].replace('simbench_',''),fmt(q['source_pu'],3),q['method'],fmt(v['over_pct']),fmt(v['under_pct']),fmt(v['conditional_over_pu'],6),fmt(v['conditional_under_pu'],6),fmt(q99,6),fmt(vals[-1],6),worst,fmt(float(zz['node_longest_over_hours'].max()),1),fmt(float(zz['node_longest_under_hours'].max()),1)])
tab('Table S4a. Voltage direction and conditional severity.',['Network','Source','Method','Over (%)','Under (%)','Cond. over (pu)','Cond. under (pu)'],[row[:7] for row in rows],'All comparisons use panel 1, seed 11, full ToU. Conditional magnitude is pooled over event-bearing customer half-hours; no event means undefined, not zero.')
tab('Table S4b. Voltage tails, worst sites and persistence.',['Network','Source','Method','q99 (pu)','Max (pu)','Worst O/U site','Longest O (h)','Longest U (h)'],[row[:3]+row[7:] for row in rows],'Site indices are 1-based household assignment slots. In SimBench, these 55 slots repeat the voltage of the corresponding 13 or 41 native load locations, and pooled voltage statistics weight those 55 assignments; they are not native bus indices. No-event worst sites are undefined. Episode lengths concatenate contiguous observed half-hours and break on missing dates; they describe half-hour-average excursions, not subinterval dynamics. Node quantiles, episode counts and p95 lengths remain in machine arrays.')
h('S5. Physical and mapping brackets')
rows=[]
for g in ('physical_brackets_seed11','mapping_seed11'):
 for q in j['selected_comparisons'][g]:
  if q['reference']!='msecont':continue
  x=q['key'];v=q['outcomes'];rows.append([g.replace('_seed11',''),str(x[5]) if x[5] is not None else f'PF {x[6]}; Z {x[7]}',fmt(v['daily_voltage_pct']['delta']['mean']),fmt(v['daily_import_peak_kw']['delta']['mean']),fmt(v['daily_export_peak_kw']['delta']['mean']),fmt(v['daily_loss_kwh']['delta']['mean'])])
tab('Table S5. Matched network-model sensitivity.',['Family','Setting','Voltage Δ (pp)','Import Δ (kW)','Export Δ (kW)','Loss Δ (kWh/day)'],rows,'DFL minus continued MSE; seed 11, panel 1. Transformer rating and parameters are unchanged during line-impedance scaling. These are bounded model sensitivity cases, not calibration to an observed physical feeder.')
h('S6. Frozen transport, matched retraining and inventory accounting')
rows=[]
def contrast(family,setting,mode,row):rows.append([family,setting,mode,str(row['household_days']),fmt(row['micro_mean_difference_aud']*100),f"{fmt(row['calendar_block95'][0]*100)} to {fmt(row['calendar_block95'][1]*100)}",fmt(row['fraction_households_benefit']*100,1)])
for setting,v in ctl['load'].items():
 for mode in ('frozen','matched'):contrast('Load',setting,mode,v[mode]['all299'])
for setting,v in ctl['wear'].items():
 for mode in ('frozen_actions_repriced','frozen_signals_reoptimized','matched_signals_reoptimized'):contrast('Wear',setting,mode.replace('_',' '),v[mode]['all299'])
for mode,v in ctl['continuous'].items():
 for outcome in ('raw_operating_contrast','inventory_adjusted_contrast'):contrast('Continuous SOC',outcome.replace('_contrast',''),mode,v[outcome]['all299'])
tab('Table S6. Complete private-cost condition matrix.',['Family','Setting','Question','Paired days','Δ (cents/day)','95% interval','Benefiting HH (%)'],rows,'DFL minus its condition-matched MSE comparator, seed 11. Frozen repricing changes no action; frozen reoptimization changes the controller objective; matched retraining changes the signal under that objective. Macro estimands and held-out/known cohorts are separately retained in control_transfer_summary. Inventory-adjusted cost is not actual retail settlement.')
p('Continuous SOC uses daily 24-hour QPs and two-day training rollout. Of the original sampled anchors, 4,088 training and 1,021 validation windows have the next day in the appropriate split. Each training window starts at 5 kWh; test carries energy across 328 complete evaluated household segments and does not reset every two days. The terminal inventory function includes both linear and quadratic terms. Segment corrections telescope as V(start)−V(end); invalid observation boundaries are common across arms. Average daily terminal energy is about 5.22 kWh for matched learners. The finite-difference gradient check includes 20 real examples, three joint net/SOC directions and three step scales, with a maximum best-scale absolute discrepancy of 5.32×10⁻¹⁰. This establishes local KKT consistency, not a globally smooth active-set map.')
h('S7. Network consequences after input and controller change')
rows=[]
for q in j['selected_comparisons']['control_sensitivities_seed11']:
 if q['reference']!='msecont':continue
 x=q['outcomes'];v=x['daily_over_pct']['delta'];rows.append([q['comparison_group'],str(q['key'][0]+1) if q['key'][0]<3 else 'Held-out',fmt(x['daily_operating_cost_aud']['delta']['mean']*100),fmt(v['mean']),f"{fmt(v['ci95'][0])} to {fmt(v['ci95'][1])}",fmt(x['daily_import_peak_kw']['delta']['mean']),fmt(x['daily_loss_kwh']['delta']['mean'])])
tab('Table S7. Control-condition private and AC outcome contrasts.',['Condition','Panel','Cost Δ (cents)','Over Δ (pp)','Over 95% interval','Import Δ (kW)','Loss Δ (kWh)'],rows,'Seed 11, full ToU, original European LV source 1.05 pu. Each group has its own matched reference; raw network private costs are not inventory-adjusted continuous economics. Panel numbering follows the main article. The matched-persistence counterexample is retained even though network outcomes worsen.')
h('S8. Export protection and system rating')
rows=[]
for q in j['export_curtailment']:
 if q.get('method') not in ('msecont','dfl'):continue
 rows.append([str(q.get('panel')),q.get('method'),str(q)])
# Exact source schema is retained, while readable cap contrasts do not depend on arbitrary dictionary order.
rows=[]
for q in j['selected_comparisons']['export_cap_seed11']:
 if q['reference']!='msecont':continue
 x=q['outcomes'];rows.append([str(q['key'][0]+1),fmt(x['daily_operating_cost_aud']['delta']['mean']*100),fmt(x['daily_over_pct']['delta']['mean']),fmt(x['daily_under_pct']['delta']['mean']),fmt(x['daily_import_peak_kw']['delta']['mean']),fmt(x['daily_export_peak_kw']['delta']['mean'])])
tab('Table S8. Equal export-limit protection layer.',['Panel','Cost Δ (cents/day)','Over Δ (pp)','Under Δ (pp)','Import Δ (kW)','Export Δ (kW)'],rows,'DFL minus continued MSE, seed 11; all three fixed panels. Actual PV curtailment and lost export income are audited per household and half-hour. Official 3 kW guidance is prospective, not historical compliance. Battery actions are frozen before this common protection layer.')
p('Curtailment is highly panel dependent. Panel 1 is almost nonbinding, Panel 2 curtails approximately 10.68–10.89 kWh/feeder-day, and Panel 3 approximately 0.090–0.115. Power-factor brackets are engineering assumptions supported by relevant operator guidance; they are not derived from these historical household meters. The main 800 kVA transformer is unchanged. In the rural 160 kVA topology, 55 historical households are aggregated to 13 native load locations, causing some nominal-rating exceedance even without voltage events; this is a constructed load-transfer stress case, not a measurement of that real circuit.')
h('S9. Geography and household distribution checks')
rows=[]
for q in j['geography_contrast']['records']:
 v=q['difference_of_method_gaps'];rows.append([q['metric'],fmt(q['narrow_method_gap'],6),fmt(q['matched_dispersed_method_gap'],6),fmt(v['mean'],6),f"{fmt(v['ci95'][0],6)} to {fmt(v['ci95'][1],6)}"])
tab('Table S9. Matched 27-household geographic-cohort check.',['Outcome','Grouped gap','Dispersed gap','Difference of gaps','95% interval'],rows,'Gap is DFL minus continued MSE. Same 27 locations and 160 dates, same known/held-out role counts. Matching uses pretest log daily gross demand and PV capacity; standardized differences are approximately −0.029 and −0.011. The dispersed cohort spans 21 postcodes with no more than two households per postcode. Units follow outcome names: AUD/owner-day, percentage points, kW or kWh/day. No real-neighborhood connectivity or causal geographic effect is inferred.')
p('The main nine deployment cells retain three-seed paired household-level cost and voltage summaries. Among full ToU owners, 3.6–7.3% have higher mean cost across fixed-panel/adoption combinations. In the 28-owner case, nonowner exposure changes are −0.3479/−0.2793/−0.2725 percentage points across the three fixed panels, versus −0.5317/−0.5103/−0.4881 for owners. Both groups can benefit on average while individual sites or customers still lose. Capacity and pretest-demand tertile cutpoints are fixed from known pretest records, not selected for subgroup significance; the full results remain descriptive without additional subgroup significance claims.')
h('S10. External data and freeze chronology')
ex=read('results/storenet_frozen_external.json');rows=[]
for setting,v in ex['scales'].items():
 for tariff,x in v['fees'].items():
  for seed in (11,23,47):
   a=x[f'paired_seed{seed}'];rows.append([setting.replace('p','.'),tariff,str(seed),fmt(a['micro_mean_difference']*100),f"{fmt(a['calendar_block95'][0]*100)} to {fmt(a['calendar_block95'][1]*100)}"])
  a=x['three_seed_mean_paired'];rows.append([setting.replace('p','.'),tariff,'Seed mean',fmt(a['micro_mean_difference']*100),f"{fmt(a['calendar_block95'][0]*100)} to {fmt(a['calendar_block95'][1]*100)}"])
tab('Table S10. All external scale, tariff and seed outcomes.',['Reference','Tariff','Training seed','Cost Δ (cents/day)','95% interval'],rows,'Each row uses 2,224 identical scored household-days across ten verified PV households in 2020; all references are normalization scales rather than verified nameplates. Negative Δ favors DFL. Three-seed rows average paired daily differences before resampling all 366 calendar positions. Flat checkpoints have a disclosed post-run hash addendum.')
p('All 20 StoreNet power CSV files were downloaded and inspected. Verified PV household IDs are 1,2,3,4,5,7,10,11,13,17. There are 3,439 complete target days before the seven-day-history requirement and 2,224 scored days after it. Mean nominal capacity is not inferred from production maxima. Original minute-grid power missingness is retained; the companion interpolated energy pipeline is unused. Public OPSD household data were also assessed, but cumulative-meter interpretation, load reconstruction and insufficient verified capacity fields made them a weaker frozen-transfer candidate; its download and screening record is retained without claiming an external result from that dataset.')
h('S11. Numerical and independent consistency checks')
p('Original strictly convex battery-layer checks include primal state and energy balance, KKT differentiation, action selection under alternative regularization, independent settlement, and an equal-buy/sell negative control. The final revision adds independent measured-cost recomputation on expanded dispatch, a real-data continuous-SOC gradient audit, inventory-boundary reconciliation and per-element export-curtailment/lost-revenue verification. AC local sensitivities are checked against full nonlinear replay and halved perturbations. These checks distinguish model implementation from field fidelity; no solver residual is treated as evidence about unknown household wiring, impedances, phase assignments, or inverter response.')
standard=read('results/revision_dispatch_audit.json');external=read('results/storenet_external_postrun_audit.json');settlement=read('research/independent_settlement_verification.json');ac=read('network_revision_audit.json')
assert standard['status']==external['status']==ac['status']=='PASS'
assert not settlement['failures'] and not settlement['not_ready'] and all(x['passed'] for x in settlement['checks'])
p(f"State and settlement checks passed for all {standard['n_completed_artifacts']} completed Ausgrid revision dispatch files and {len(external['checked_dispatch_files'])} external dispatch files. External recomputation had zero stored-cost discrepancy; the largest rounded-state bound and cyclic-end discrepancies were {external['max_storage_rounded_soc_bound_violation_kwh']:.2e} and {external['max_storage_rounded_cyclic_end_error_kwh']:.2e} kWh. An additional independent settlement implementation recomputed all {len(settlement['checks'])} expanded comparison files directly from observed load, generation and saved charge/discharge actions, with no failed or unfinished file in that comparison.")
p(f"The network revision contains {ac['new_scenarios']} completed scenario results: {ac['newly_executed_ac_replays']} new nonlinear AC replays and {ac['reused_original_geo_replays_with_new_common_mask']} original geographic replays restricted to the new common-date mask. All new replays converged, and the maximum absolute active-power balance residual was {ac['maximum_balance_residual_kw']:.2e} kW. Numerical convergence does not imply satisfaction of voltage or equipment constraints. Export checks include curtailed generation and foregone export revenue.")
p('The local reproduction package contains source-data acquisition records, model weights, derived inputs, saved dispatch, numerical audits and the code required to reconstruct the reported tables and figures. It supports independent cost, observation-mask and checkpoint checks. Fresh training from source data additionally requires the documented public-data acquisition and cache-generation steps. Source-data and software licenses are recorded with the corresponding materials; the package is a local research artifact and has not been assigned a public DOI.')
for b in bs:
 if 'text' in b:
  b['text']=b['text'].replace('3,439 complete target days','3,439 target days passing interval quality').replace('Original minute-grid power missingness is retained;', 'A half-hour must contain at least 27 of 30 valid minutes in each required channel; available power observations are averaged without interpolation. Original minute-grid power missingness is retained;')
(M/'supplement_blocks.json').write_text(json.dumps({'title':'Supplementary methods and results','blocks':bs},ensure_ascii=False,indent=2),encoding='utf-8')
def plain(b):return b.get('text',b.get('caption',''))+ ('\n'+' | '.join(b['headers'])+'\n'+'\n'.join(' | '.join(row) for row in b['rows'])+'\n'+b['note'] if b['type']=='table' else '')
(M/'supplement_full.txt').write_text('\n\n'.join(plain(b) for b in bs),encoding='utf-8')
print(json.dumps({'blocks':len(bs),'tables':sum(b['type']=='table' for b in bs)}))
